spring:
  datasource:
    url: ${DB-URL:jdbc:postgresql://localhost:5432/GymManager}
    username: ${DB_USER:user}
    password: ${DB_PASS:"password"}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: gymmanager

server:
  port: 8080

security:
  jwt:
    secret: "mySuperSecretKeyForGymManager123456789!"
    expiration-ms: 86400000
